#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cleanuparr"
name = "Cleanuparr"
description.en = "Advanced download manager for the Servarr ecosystem"
description.fr = "Gestionnaire avancé de téléchargements pour l'écosystème Servarr"

version = "2.10.9~ynh1"

maintainers = ["Jean-Benoit"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://cleanuparr.github.io/Cleanuparr/"
admindoc = "https://cleanuparr.github.io/Cleanuparr/docs/installation/"
userdoc = "https://cleanuparr.github.io/Cleanuparr/docs/"
code = "https://github.com/Cleanuparr/Cleanuparr"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "350M"
ram.build = "512M"
ram.runtime = "512M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/cleanuparr"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources.main]
    in_subdir = true
    format = "zip"
    amd64.url = "https://github.com/Cleanuparr/Cleanuparr/releases/download/v2.10.9/Cleanuparr-2.10.9-linux-amd64.zip"
    amd64.sha256 = "fa92b608ff79c49f329877829b14ce9a752c9a7c431720ba5f1b0252c32c5bb7"
    arm64.url = "https://github.com/Cleanuparr/Cleanuparr/releases/download/v2.10.9/Cleanuparr-2.10.9-linux-arm64.zip"
    arm64.sha256 = "b2a079bf652fc2917b8a0d1e18b94708fa7b816aa96b9a74dfef87a047d5de22"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/Cleanuparr/Cleanuparr"
    autoupdate.asset.amd64 = "Cleanuparr-.*-linux-amd64\\.zip"
    autoupdate.asset.arm64 = "Cleanuparr-.*-linux-arm64\\.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["logs", "venv"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 11011

    [resources.apt]
    packages = "ca-certificates, libicu-dev, libssl-dev, python3, python3-venv"
